// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMsnbENv0PBwFjQq9fttIqyntHYmqPUt4',
    appId: '1:768704242589:web:e17715fb0462d83bcfc574',
    messagingSenderId: '768704242589',
    projectId: 'fireabasetest123',
    authDomain: 'fireabasetest123.firebaseapp.com',
    storageBucket: 'fireabasetest123.firebasestorage.app',
    measurementId: 'G-PZS6GEC1DW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJQ1CgO8m72VVyKLwVq6s1wp3fMD8U1Us',
    appId: '1:768704242589:android:45fd649216540ebdcfc574',
    messagingSenderId: '768704242589',
    projectId: 'fireabasetest123',
    storageBucket: 'fireabasetest123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfSpWD6OHlt2nWLLvcWU_XURO8dyUSV0U',
    appId: '1:768704242589:ios:a5c6ef72658231b7cfc574',
    messagingSenderId: '768704242589',
    projectId: 'fireabasetest123',
    storageBucket: 'fireabasetest123.firebasestorage.app',
    iosBundleId: 'com.example.fireBse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfSpWD6OHlt2nWLLvcWU_XURO8dyUSV0U',
    appId: '1:768704242589:ios:a5c6ef72658231b7cfc574',
    messagingSenderId: '768704242589',
    projectId: 'fireabasetest123',
    storageBucket: 'fireabasetest123.firebasestorage.app',
    iosBundleId: 'com.example.fireBse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMsnbENv0PBwFjQq9fttIqyntHYmqPUt4',
    appId: '1:768704242589:web:72d14bb91a333c60cfc574',
    messagingSenderId: '768704242589',
    projectId: 'fireabasetest123',
    authDomain: 'fireabasetest123.firebaseapp.com',
    storageBucket: 'fireabasetest123.firebasestorage.app',
    measurementId: 'G-9XWF1L4E0R',
  );
}
